// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_post_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPostUser = `-- name: GetPostUser :many
SELECT id, created_at, updated_at, name FROM users
WHERE id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetPostUserParams struct {
	ID    uuid.UUID
	Limit int32
}

func (q *Queries) GetPostUser(ctx context.Context, arg GetPostUserParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getPostUser, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
